version: "2"
linters:
  default: standard
  enable:
    - testifylint
    - sloglint
    - nilerr
    - bodyclose
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    sloglint:
      context: "all"
  exclusions:
    presets:
      - std-error-handling
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pddg/photon-container
