services:
  photon:
    image: ghcr.io/pddg/photon:latest
    environment:
      # Where to download the data from
      # Only supports archives for photon 1.x or later.
      - PHOTON_AGENT_DATABASE_URL=https://download1.graphhopper.com/public/europe/andorra/photon-db-andorra-1.0-latest.tar.bz2
      - PHOTON_AGENT_PHOTON_LISTEN_IP=0.0.0.0
    volumes:
      # Mount the photon data volume
      # /photon/photon_data is the default path for the index data
      - photon_data:/photon/photon_data
    restart: unless-stopped
    ports:
      # management port
      - "8080:8080"
      # photon port
      - "2322:2322"
volumes:
  photon_data:
