apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./01-sts.yaml
  - ./02-svc.yaml

images:
  - name: ghcr.io/pddg/photon
    # It is recommended to use the fixed tag for production
    newTag: latest
